### ISSUE TITLE
gdcCEAnalysis 构建ceRNA bug

### ISSUE THREAD

**Issue by sherylwalker** [Jialab-UCR/GDCRNATools#4]
用gdcCEAnalysis的时候，lnc.target设‘spongeScan’会报错，设为‘starBase’和‘miRcode’想去甚远。starBase最后的node在33左右，而用miRcode会有700+ node。而且设定了deMIR，运算出来的结果还是包含了非deMIR里的数据

**Comment by PKUDrChao** [comment]
请问怎么解决的
