### ISSUE TITLE
Error while using gdcClinicalMerge

### ISSUE THREAD

**Issue by ZhangQiuxue** [Jialab-UCR/GDCRNATools#5]
I download clinical data fellowed the [GDCRNATools Manual](http://bioconductor.org/packages/devel/bioc/vignettes/GDCRNATools/inst/doc/GDCRNATools.html) 
I got a error when using gdcClinicalMerge(). The error is like this:
```
> clinicalDa <- gdcClinicalMerge(path = clinicaldir, key.info = TRUE)
############### Merging Clinical data ###############

Error in apply(t3, 2, function(v) max(as.numeric(v))) : 
  dim(X) must have a positive length
```

**Comment by Jialab-UCR** [comment]
@ZhangQiuxue The bug has been fixed and please install the newest version. Thanks

**Comment by ZhangQiuxue** [comment]
OK ,Thanks
